name: dynamic-transformer
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - libcxx=21.1.8=hb4ce287_0
  - libexpat=2.7.4=h50f4ffc_0
  - libffi=3.4.4=hca03da5_1
  - libmpdec=4.0.0=h80987f9_0
  - libzlib=1.3.1=h5f15de7_0
  - lz4-c=1.9.4=h313beb8_1
  - ncurses=6.5=hee39554_0
  - openssl=3.0.19=ha0b305a_0
  - packaging=25.0=py314hca03da5_1
  - pip=26.0.1=pyhc872135_0
  - python=3.14.2=h1858270_101_cp314
  - python_abi=3.14=2_cp314
  - readline=8.3=h0b18652_0
  - setuptools=80.10.2=py314hca03da5_0
  - sqlite=3.51.1=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - tzdata=2025c=he532380_0
  - wheel=0.46.3=py314hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h817c040_0
  - pip:
      - annotated-doc==0.0.4
      - anyio==4.12.1
      - certifi==2026.1.4
      - click==8.3.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - filelock==3.24.3
      - fonttools==4.61.1
      - fsspec==2026.2.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.4.1
      - idna==3.11
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - mdurl==0.1.2
      - mpmath==1.3.0
      - networkx==3.6.1
      - numpy==2.4.2
      - pillow==12.1.1
      - pygments==2.19.2
      - pyparsing==3.3.2
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.3
      - regex==2026.2.19
      - rich==14.3.3
      - safetensors==0.7.0
      - shellingham==1.5.4
      - six==1.17.0
      - sympy==1.14.0
      - tokenizers==0.22.2
      - torch==2.10.0
      - torchvision==0.25.0
      - tqdm==4.67.3
      - transformers==5.2.0
      - typer==0.24.1
      - typer-slim==0.24.0
      - typing-extensions==4.15.0
