seed: 42
num_epochs: 30
use_logits: false
accum_steps: 1
checkpoints_dir: "checkpoints/dynamicvit"
checkpoints_freq: 10
loss:
  lambda_n: 1.0
  eps: 1.0
  eps_rate: 1.0
  eps_min: 0.01
  eps_update_freq: 2
optimizer:
  lr: 7.5e-4
  betas: [0.9, 0.999]
  weight_decay: 1e-4
scheduler:
  warmup_epochs: 5
early_stopping: null
data:
  data_dir: "data"
  train_bs: 512
  val_bs: 512
