seed: 42
num_epochs: 40
accum_steps: 1
checkpoints_dir: "checkpoints/simplevit"
checkpoints_freq: 10
loss: null
optimizer:
  lr: 5e-4
  betas: [0.9, 0.999]
  weight_decay: 1e-4
scheduler:
  warmup_epochs: 5
early_stopping: null
data:
  data_dir: "data"
  train_bs: 512
  val_bs: 512
